---
# The catalog for intended distribution.
# Can be either "certified-operators" or "redhat-marketplace"
organization: redhat-marketplace

# tests to ignore for certain partners (until static checker's bugs are fixed):
tests:
  - name: check_operator_name
    ignore_operators:
      - ^falcon-operator-rhmp
