apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zabbixagents.kubernetes.zabbix.com
spec:
  group: kubernetes.zabbix.com
  names:
    kind: ZabbixAgent
    listKind: ZabbixAgentList
    plural: zabbixagents
    singular: zabbixagent
    shortNames:
    - za
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        status:
          description: Deployment status information
          type: object
          properties:
            phase:
              description: Status of deployment operation
              type: string
              enum:
                - "Running"
                - "Pending"
                - "Failed"
            reason:
              description: Error description during deployment
              type: string
            conditions:
              type: object
        spec:
          description: Configuration parameters for Zabbix component
          type: object
          properties:
            version:
              description: Version of Zabbix agent
              type: string
              enum:
                - "latest"
            agent_env:
              description: Configuration parameters for Zabbix agent
              type: object
              properties:
                allow_privileged:
                  description: Enable privileged mode
                  type: boolean
                server_host:
                  description: IP address, optionally in CIDR notation, or hostname of main Zabbix server or proxy for passive and active checks
                  type: string
                  minLength: 1
                hostname:
                  description: Unique, case sensitive hostname
                  type: string
                debug_level:
                  description: Specifies debug level
                  type: integer
                  minimum: 0
                  maximum: 5
                enable_remote_commands:
                  description: Whether remote commands from Zabbix server are allowed
                  type: integer
                  minimum: 0
                  maximum: 1
                log_remote_commands:
                  description: Enable logging of executed shell commands as warnings
                  type: integer
                  minimum: 0
                  maximum: 1
                passive_allow:
                  description: Enable / Disable passive checks
                  type: string
                  enum:
                    - "true"
                    - "false"
                passive_servers:
                  description: List of comma delimited IP addresses, optionally in CIDR notation, or hostnames of Zabbix servers and Zabbix proxies
                  type: string
                active_allow:
                  description: Enable / Disable active checks
                  type: string
                  enum:
                    - "true"
                    - "false"
                activeservers:
                  description: IP:port (or hostname:port) of Zabbix server or Zabbix proxy for active checks
                  type: string
                start_agents:
                  description: Number of pre-forked instances of zabbix_agentd that process passive checks
                  type: integer
                  minimum: 0
                  maximum: 100
                hostname_item:
                  description: Optional parameter that defines a Zabbix agent item used for getting host name
                  type: string
                metadata:
                  description: Optional parameter that defines host metadata
                  type: string
                metadata_item:
                  description: Optional parameter that defines a Zabbix agent item used for getting host metadata
                  type: string
                alias:
                  description: Sets an alias for an item key. It can be used to substitute long and complex item key with a smaller and simpler one.
                  type: string
                timeout:
                  description: Spend no more than Timeout seconds on processing
                  type: integer
                  minimum: 1
                  maximum: 30
              required:
              - server_host
